/**
 * Canonical frontend boundary for Firebase persistence.
 *
 * React components import this facade instead of the SDK adapter directly.
 * The existing implementation remains in lib/firebase.ts so production paths,
 * legacy rooms and deployed Functions contracts stay unchanged.
 */
export {
  archiveSession,
  copyQuizPackToWorkspace,
  changeLeaderAccess,
  createSession,
  createSessionRecord,
  defaultDiagnosticTemplateSelection,
  defaultRoomTitle,
  diagnosticGameTypeId,
  diagnosticPackId,
  diagnosticProductId,
  ensureAuth,
  ensureParticipantRoomData,
  firebaseReady,
  isPlatformOwner,
  getOwnerAdminDashboard,
  joinSession,
  loginLeader,
  logoutLeader,
  markOwnerNotificationsRead,
  markPersonalViewed,
  platformProductDefaults,
  ParticipantAnswerError,
  quizGameTypeId,
  registerLeader,
  saveAnswer,
  saveGlobalPackAsOwner,
  saveProductAsOwner,
  saveWorkspacePack,
  saveWorkspaceProductAsOwner,
  publishSafePackCatalogueAsOwner,
  seedDefaultGlobalPack,
  setLeaderStatusAsOwner,
  subscribeAuthUser,
  subscribeGlobalPack,
  subscribeLeaderProfile,
  subscribeOwnerNotifications,
  subscribeParticipantQuestionSet,
  subscribeParticipantQuizResult,
  subscribeParticipantRecord,
  subscribePlatformArchives,
  subscribePlatformFeedback,
  subscribePlatformGlobalPacks,
  subscribePlatformLeaders,
  subscribePlatformProducts,
  subscribePlatformSessions,
  subscribePlatformWorkspaceProducts,
  subscribePlatformWorkspaces,
  subscribePublicRoom,
  subscribePublishedGlobalPacks,
  subscribeRoomLobby,
  subscribeRoomQuizResults,
  subscribeSession,
  subscribeSessionArchives,
  subscribeWorkspace,
  subscribeWorkspacePack,
  subscribeWorkspaceQuizPacks,
  updatePhase,
  updateRoomTitle,
  updateSessionPilotCounts,
  waitForAuthPersistence,
} from '../lib/firebase'

export type { RoomPilotDetails } from '../lib/firebase'
export type { OwnerDashboard, OwnerRegistrationNotification } from '../lib/firebase'
