import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import type { ModeLandingScreenProps, ModeParticipantFlowProps, ModeSetupScreenProps } from '../contracts'
import type { ParticipantQuestionScreenProps } from '../participantTypes'
import { Button, LoadingState, StatusBadge, Surface } from '../../components/DesignSystem'
import { createJoinUrl } from '../../lib/urls'
import { go, queryRoom } from '../../core/navigation'
import {
  copyVerseMatchPack, createVerseMatchRoom, deleteVerseMatchPack, finishVerseMatchGame,
  getVerseMatchLibrary, joinVerseMatchRoom, nextVerseMatchRound, prepareVerseParticipantAuth,
  revealVerseMatchAnswer, saveVerseMatchPack, startVerseMatchGame, submitVerseMatchCard,
  subscribeVerseAudience, subscribeVerseHost, subscribeVerseParticipant,
} from './repository'
import type { VerseAudienceView, VerseDifficulty, VerseDirection, VerseEntry, VerseHostView, VersePack, VerseParticipantView, VerseResult } from './types'
import { countAvailableVerses, validateVersePack } from './validation'

const difficultyLabel: Record<VerseDifficulty, string> = { easy: 'Лёгкая', medium: 'Средняя', hard: 'Сложная' }
const directionLabel: Record<VerseDirection, string> = { ends: 'На карточках окончания', starts: 'На карточках начала', mixed: 'Смешанный режим 50/50' }
const blankEntry = (index: number): VerseEntry => ({ id: `verse-${Date.now()}-${index}`, bookId: 'PRO', book: 'Притчи', chapter: 1, verse: '1', reference: 'Притчи 1:1', translation: 'Синодальный перевод', fullText: '', start: '', end: '', difficulty: 'easy', enabled: true, verificationStatus: 'draft' })
const blankPack = (): VersePack => ({ packId: '', version: 1, title: 'Новый набор', description: '', translation: 'Синодальный перевод', sourceUrl: '', license: '', status: 'draft', entries: [] })
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Не удалось выполнить действие.'

function ResultsTable({ rows, interim }: { rows: VerseResult[]; interim: boolean }) {
  return <div className="verse-results-wrap"><table className="verse-results"><thead><tr><th>Место</th><th>Участник</th><th>Верно</th><th>Ошибки</th><th>Пропуски</th><th>Осталось</th></tr></thead><tbody>{rows.map(row => <tr key={row.participantId} className={row.perfect ? 'is-perfect' : ''}><td>{interim ? '—' : row.place === 1 ? '🏆 1' : row.place}</td><td>{row.nickname}</td><td>{row.correct}/{row.total}</td><td>{row.errors}</td><td>{row.missed}</td><td>{row.remaining}</td></tr>)}</tbody></table></div>
}

export function VerseMatchLibraryPanel({ admin = false }: { admin?: boolean }) {
  const [system, setSystem] = useState<VersePack[]>([]); const [workspace, setWorkspace] = useState<VersePack[]>([])
  const [editing, setEditing] = useState<VersePack | null>(null); const [selectedEntry, setSelectedEntry] = useState(0)
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const library = await getVerseMatchLibrary(); setSystem(library.system); setWorkspace(library.workspace) } catch (reason) { setError(errorText(reason)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const updateEntry = (patch: Partial<VerseEntry>) => setEditing(current => current ? ({ ...current, entries: current.entries.map((entry, index) => index === selectedEntry ? { ...entry, ...patch } : entry) }) : current)
  const validation = editing ? validateVersePack(editing) : null
  const save = async () => {
    if (!editing) return; setBusy(true); setError(''); setNotice('')
    try { const result = await saveVerseMatchPack(admin ? 'system' : 'workspace', editing); setEditing(result.pack); setNotice('Набор сохранён.'); await load() } catch (reason) { setError(errorText(reason)) } finally { setBusy(false) }
  }
  if (loading) return <LoadingState eyebrow="БИБЛИОТЕКА" title="Загружаем наборы…" />
  return <div className="verse-library">
    <div className="verse-library-toolbar"><div><h3>{admin ? 'Общая библиотека стихов' : 'Наборы «Собери стих»'}</h3><p>{admin ? 'Публикуйте только проверенные тексты.' : 'Скопируйте общий набор или создайте собственный.'}</p></div><Button secondary onClick={() => { setEditing(blankPack()); setSelectedEntry(0) }}>Новый набор</Button></div>
    {error && <p className="connection-warning" role="alert">{error}</p>}{notice && <p className="verse-success">{notice}</p>}
    <div className="verse-pack-grid">
      {system.map(pack => <Surface className="verse-pack-card" key={`system-${pack.packId}`}><StatusBadge>{pack.status === 'published' ? 'ОПУБЛИКОВАН' : 'ЧЕРНОВИК'}</StatusBadge><h4>{pack.title}</h4><p>{pack.entries.length} стихов · версия {pack.version}</p><div className="verse-inline-actions">{admin ? <Button secondary onClick={() => { setEditing(structuredClone(pack)); setSelectedEntry(0) }}>Редактировать</Button> : <Button secondary disabled={busy} onClick={() => { setBusy(true); void copyVerseMatchPack(pack.packId).then(() => { setNotice('Копия добавлена в ваши наборы.'); return load() }).catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }}>Скопировать</Button>}</div></Surface>)}
      {!admin && workspace.map(pack => <Surface className="verse-pack-card" key={`workspace-${pack.packId}`}><StatusBadge tone="muted">МОЙ НАБОР</StatusBadge><h4>{pack.title}</h4><p>{pack.entries.length} стихов · {pack.status}</p><div className="verse-inline-actions"><Button secondary onClick={() => { setEditing(structuredClone(pack)); setSelectedEntry(0) }}>Редактировать</Button><Button danger disabled={busy} onClick={() => { if (!window.confirm(`Удалить набор «${pack.title}»?`)) return; setBusy(true); void deleteVerseMatchPack(pack.packId).then(load).catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }}>Удалить</Button></div></Surface>)}
    </div>
    {editing && <Surface className="verse-editor"><div className="verse-editor-head"><div><p className="eyebrow">РЕДАКТОР НАБОРА</p><h3>{editing.title}</h3></div><Button secondary onClick={() => setEditing(null)}>Закрыть</Button></div>
      <div className="verse-form-grid"><label>Название<input value={editing.title} onChange={event => setEditing({ ...editing, title: event.target.value })} /></label><label>Статус<select value={editing.status} onChange={event => setEditing({ ...editing, status: event.target.value as VersePack['status'] })}><option value="draft">Черновик</option><option value="published">Опубликован</option><option value="archived">Архив</option></select></label><label className="wide">Описание<textarea value={editing.description} onChange={event => setEditing({ ...editing, description: event.target.value })} /></label><label>Перевод<input value={editing.translation} onChange={event => setEditing({ ...editing, translation: event.target.value })} /></label><label>Лицензия<input value={editing.license} onChange={event => setEditing({ ...editing, license: event.target.value })} /></label><label className="wide">Источник<input value={editing.sourceUrl} onChange={event => setEditing({ ...editing, sourceUrl: event.target.value })} /></label></div>
      <div className="verse-entry-layout"><aside><div className="verse-entry-list-head"><b>Стихи ({editing.entries.length})</b><button type="button" onClick={() => { setEditing({ ...editing, entries: [...editing.entries, blankEntry(editing.entries.length)] }); setSelectedEntry(editing.entries.length) }}>+ Добавить</button></div>{editing.entries.map((entry, index) => <button type="button" className={index === selectedEntry ? 'selected' : ''} key={`${entry.id}-${index}`} onClick={() => setSelectedEntry(index)}>{entry.reference || `Стих ${index + 1}`}<small>{difficultyLabel[entry.difficulty]} · {entry.verificationStatus}</small></button>)}</aside>
        {editing.entries[selectedEntry] ? <div className="verse-entry-form"><div className="verse-form-grid"><label>ID<input value={editing.entries[selectedEntry].id} onChange={event => updateEntry({ id: event.target.value })} /></label><label>Ссылка<input value={editing.entries[selectedEntry].reference} onChange={event => updateEntry({ reference: event.target.value })} /></label><label>Книга<input value={editing.entries[selectedEntry].book} onChange={event => updateEntry({ book: event.target.value })} /></label><label>Код книги<input value={editing.entries[selectedEntry].bookId} onChange={event => updateEntry({ bookId: event.target.value })} /></label><label>Глава<input type="number" min="1" value={editing.entries[selectedEntry].chapter} onChange={event => updateEntry({ chapter: Number(event.target.value) })} /></label><label>Стих<input value={editing.entries[selectedEntry].verse} onChange={event => updateEntry({ verse: event.target.value })} /></label><label className="wide">Полный текст<textarea value={editing.entries[selectedEntry].fullText} onChange={event => updateEntry({ fullText: event.target.value })} /></label><label className="wide">Начало<textarea value={editing.entries[selectedEntry].start} onChange={event => updateEntry({ start: event.target.value })} /></label><label className="wide">Окончание<textarea value={editing.entries[selectedEntry].end} onChange={event => updateEntry({ end: event.target.value })} /></label><label>Сложность<select value={editing.entries[selectedEntry].difficulty} onChange={event => updateEntry({ difficulty: event.target.value as VerseDifficulty })}>{Object.entries(difficultyLabel).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Проверка<select value={editing.entries[selectedEntry].verificationStatus} onChange={event => updateEntry({ verificationStatus: event.target.value as VerseEntry['verificationStatus'] })}><option value="draft">Не проверен</option><option value="verified">Проверен</option><option value="rejected">Отклонён</option></select></label><label className="verse-check"><input type="checkbox" checked={editing.entries[selectedEntry].enabled} onChange={event => updateEntry({ enabled: event.target.checked })} /> Включён</label></div><Button danger onClick={() => { const entries = editing.entries.filter((_, index) => index !== selectedEntry); setEditing({ ...editing, entries }); setSelectedEntry(Math.max(0, selectedEntry - 1)) }}>Удалить стих</Button></div> : <p>Добавьте первый стих.</p>}</div>
      <div className="verse-validation"><b>{validation?.valid ? '✓ Набор прошёл локальную проверку' : `Найдено проблем: ${validation?.issues.length || 0}`}</b>{validation?.issues.slice(0, 8).map((issue, index) => <span key={`${issue.path}-${index}`}>{issue.path}: {issue.message}</span>)}</div><Button disabled={busy || (editing.status === 'published' && !validation?.valid)} onClick={() => void save()}>{busy ? 'Сохраняем…' : 'Сохранить набор'}</Button>
    </Surface>}
  </div>
}

export function VerseLandingScreen({ onSetup }: ModeLandingScreenProps) {
  return <div className="verse-landing"><Surface className="mode-intro verse-intro"><p className="eyebrow">БИБЛЕЙСКАЯ КОМАНДНАЯ ИГРА</p><h2>Собери стих</h2><p>Участники получают уникальные начала или окончания стихов и на скорость находят пару к фрагменту на общем экране.</p><ol><li>Выберите проверенный набор и сложность.</li><li>Раздача и проверка проходят только на сервере.</li><li>Первое место получают только участники без единой ошибки или пропуска.</li></ol><Button onClick={onSetup}>Создать комнату</Button></Surface><VerseMatchLibraryPanel /></div>
}

export function VerseSetupScreen({ onBack, defaultTitle, onCreated }: ModeSetupScreenProps) {
  const [packs, setPacks] = useState<VersePack[]>([]); const [packId, setPackId] = useState(''); const [title, setTitle] = useState(defaultTitle || 'Собери стих')
  const [difficulty, setDifficulty] = useState<VerseDifficulty>('easy'); const [cards, setCards] = useState<5 | 7 | 10>(5); const [direction, setDirection] = useState<VerseDirection>('ends')
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { void getVerseMatchLibrary().then(value => { const available = [...value.system, ...value.workspace].filter(pack => pack.status === 'published'); setPacks(available); setPackId(available[0]?.packId || '') }).catch(reason => setError(errorText(reason))).finally(() => setLoading(false)) }, [])
  const pack = packs.find(item => item.packId === packId); const available = pack ? countAvailableVerses(pack, difficulty) : 0; const maxPlayers = Math.floor(available / cards)
  if (loading) return <LoadingState eyebrow="СОБЕРИ СТИХ" title="Загружаем наборы…" />
  return <Surface className="verse-setup"><div className="verse-form-grid"><label className="wide">Название комнаты<input value={title} maxLength={80} onChange={event => setTitle(event.target.value)} /></label><label className="wide">Набор<select value={packId} onChange={event => setPackId(event.target.value)}>{packs.map(item => <option key={item.packId} value={item.packId}>{item.title} · v{item.version}</option>)}</select></label><label>Сложность<select value={difficulty} onChange={event => setDifficulty(event.target.value as VerseDifficulty)}>{Object.entries(difficultyLabel).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Карточек игроку<select value={cards} onChange={event => setCards(Number(event.target.value) as 5 | 7 | 10)}><option value="5">5</option><option value="7">7</option><option value="10">10</option></select></label><label className="wide">Направление<select value={direction} onChange={event => setDirection(event.target.value as VerseDirection)}>{Object.entries(directionLabel).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>
    <div className="verse-capacity"><b>{available} проверенных стихов</b><span>Вместимость: до {maxPlayers} участников · раундов на игрока: {cards}</span>{maxPlayers < 1 && <p className="connection-warning">В выбранной сложности недостаточно стихов.</p>}</div>{error && <p className="connection-warning">{error}</p>}<div className="verse-inline-actions"><Button secondary onClick={onBack}>Назад</Button><Button disabled={busy || !packId || maxPlayers < 1} onClick={() => { setBusy(true); setError(''); void createVerseMatchRoom({ title, packId, difficulty, cardsPerPlayer: cards, direction }).then(({ roomId }) => onCreated?.(roomId, `/verse-host?room=${roomId}`)).catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }}>{busy ? 'Создаём…' : 'Создать комнату'}</Button></div>
  </Surface>
}

export function VerseHostPage({ room }: { room: string }) {
  const [view, setView] = useState<VerseHostView | null>(null); const [qr, setQr] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const joinUrl = createJoinUrl(room)
  useEffect(() => subscribeVerseHost(room, setView, reason => setError(reason.message)), [room])
  useEffect(() => { void QRCode.toDataURL(joinUrl, { width: 320, margin: 1, errorCorrectionLevel: 'M' }).then(setQr) }, [joinUrl])
  const act = (operation: () => Promise<unknown>) => { setBusy(true); setError(''); void operation().catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }
  if (!view) return <main className="verse-page"><LoadingState eyebrow="СОБЕРИ СТИХ" title="Подключаем комнату…" description={error} /></main>
  const round = view.currentRound; const canStart = view.participants.length > 0 && view.capacity.available >= view.capacity.required
  return <main className="verse-page verse-host"><header className="verse-page-header"><div><p className="eyebrow">СОБЕРИ СТИХ · DEV PREVIEW</p><h1>{view.title}</h1><p>Код комнаты <strong>{view.roomId}</strong> · {view.pack.title} · {difficultyLabel[view.config.difficulty]}</p></div><div className="verse-inline-actions"><Button secondary onClick={() => window.open(`/verse-stage?room=${room}`, 'verse-stage')}>Экран аудитории</Button><Button secondary onClick={() => go('/host?tab=main')}>В панель</Button></div></header>
    {error && <p className="connection-warning">{error}</p>}
    {view.phase === 'lobby' && <div className="verse-host-grid"><Surface className="verse-qr"><img src={qr} alt="QR-код комнаты" /><code>{joinUrl}</code><Button secondary onClick={() => void navigator.clipboard.writeText(joinUrl)}>Скопировать ссылку</Button></Surface><Surface><p className="eyebrow">ЛОББИ</p><h2>{view.participants.length} участников</h2><p>Требуется {view.capacity.required} из {view.capacity.available} стихов. Максимум для настроек: {view.capacity.maxPlayers} игроков.</p><ul className="verse-people">{view.participants.map(person => <li key={person.id}><b>{person.nickname}</b><span>готов</span></li>)}</ul><Button disabled={busy || !canStart} onClick={() => act(() => startVerseMatchGame(room))}>Начать игру</Button>{!canStart && view.participants.length > 0 && <p className="connection-warning">Уменьшите число игроков/карточек или выберите более крупный набор.</p>}</Surface></div>}
    {view.phase === 'live' && <><div className="verse-metrics"><Surface><b>{view.roundNumber}</b><span>текущий раунд</span></Surface><Surface><b>{view.remainingCards}</b><span>карточек осталось</span></Surface><Surface><b>{view.history.length}</b><span>завершено</span></Surface></div><Surface className={`verse-prompt ${round?.status === 'revealed' ? 'is-revealed' : ''}`}><p className="eyebrow">{round?.status === 'revealed' ? 'ОТВЕТ' : round?.promptDirection === 'start' ? 'НАЙДИТЕ НАЧАЛО' : 'НАЙДИТЕ ОКОНЧАНИЕ'}</p>{round?.status === 'revealed' ? <><blockquote>{round.fullText}</blockquote><h3>{round.reference}</h3><p>{round.outcome === 'correct' ? `Верно${round.answeredByName ? ` · ${round.answeredByName}` : ''}` : 'Ответ не найден'}</p><Button disabled={busy} onClick={() => act(() => nextVerseMatchRound(room))}>Следующий раунд</Button></> : <><blockquote>{round?.promptText}</blockquote><p>Участники выбирают подходящую карточку на своих устройствах.</p><Button secondary disabled={busy} onClick={() => act(() => revealVerseMatchAnswer(room))}>Показать ответ</Button></>}</Surface><Surface><h3>Живой прогресс</h3><div className="verse-progress-list">{view.participants.map(person => <div key={person.id}><b>{person.nickname}</b><span>✓ {person.correct} · ошибки {person.errors} · пропуски {person.missed} · осталось {person.remaining}</span></div>)}</div><Button danger disabled={busy} onClick={() => { if (window.confirm('Завершить игру досрочно? Рейтинг останется промежуточным.')) act(() => finishVerseMatchGame(room, true)) }}>Завершить досрочно</Button></Surface></>}
    {(view.phase === 'completed' || view.phase === 'closed') && <Surface className="verse-final"><p className="eyebrow">{view.endedEarly ? 'ПРОМЕЖУТОЧНЫЕ РЕЗУЛЬТАТЫ' : 'ИГРА ЗАВЕРШЕНА'}</p><h2>{view.endedEarly ? 'Игра остановлена досрочно' : 'Итоги «Собери стих»'}</h2><ResultsTable rows={view.results || []} interim={view.endedEarly} />{view.phase === 'completed' && <Button onClick={() => act(() => finishVerseMatchGame(room, false))}>Закрыть и сохранить комнату</Button>}</Surface>}
  </main>
}

export function VerseParticipantFlow({ room }: ModeParticipantFlowProps) {
  const [uid, setUid] = useState(''); const [view, setView] = useState<VerseParticipantView | null>(null); const [nickname, setNickname] = useState(''); const [selected, setSelected] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let stop: (() => void) | undefined; void prepareVerseParticipantAuth().then(id => { setUid(id); stop = subscribeVerseParticipant(room, id, setView, reason => setError(reason.message)) }).catch(reason => setError(errorText(reason))); return () => stop?.() }, [room])
  const available = view?.cards.filter(card => card.status === 'available') || []; const closed = view?.cards.filter(card => card.status !== 'available') || []
  const submit = () => { if (!view?.currentRound || !selected) return; setBusy(true); setError(''); void submitVerseMatchCard(room, selected, view.currentRound.roundId, view.currentRound.version).then(result => { if (!result.correct) setError('Не совпало. Эта карточка закрыта — попробуйте другую в следующем раунде.'); setSelected('') }).catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }
  if (!uid && !error) return <main className="verse-participant"><LoadingState eyebrow="СОБЕРИ СТИХ" title="Подключаем…" /></main>
  if (!view) return <main className="verse-participant"><Surface className="verse-join"><p className="eyebrow">КОМНАТА {room}</p><h1>Собери стих</h1><p>Введите имя. После старта вы получите уникальные карточки.</p><form onSubmit={event => { event.preventDefault(); if (nickname.trim().length < 2) return; setBusy(true); setError(''); void joinVerseMatchRoom(room, nickname.trim()).catch(reason => setError(errorText(reason))).finally(() => setBusy(false)) }}><label>Ваше имя<input value={nickname} maxLength={30} autoComplete="nickname" onChange={event => setNickname(event.target.value)} /></label><button className="button" disabled={busy || nickname.trim().length < 2}>{busy ? 'Подключаем…' : 'Войти в игру'}</button></form>{error && <p className="connection-warning">{error}</p>}</Surface></main>
  return <main className="verse-participant"><header><p className="eyebrow">{view.title}</p><h1>{view.nickname}</h1><div className="verse-counter-row"><span>✓ {view.stats.correct}</span><span>Ошибки {view.stats.errors}</span><span>Пропуски {view.stats.missed}</span></div></header>
    {view.phase === 'lobby' && <Surface className="verse-wait"><h2>Вы в комнате</h2><p>Ведущий скоро запустит игру. Карточки появятся автоматически.</p></Surface>}
    {view.phase === 'live' && <><Surface className="verse-mobile-prompt"><p className="eyebrow">ОБЩИЙ ФРАГМЕНТ</p><blockquote>{view.currentRound?.status === 'revealed' ? view.currentRound.fullText : view.currentRound?.promptText || 'Следующий раунд готовится…'}</blockquote>{view.currentRound?.status === 'revealed' && <b>{view.currentRound.reference}</b>}</Surface><section><div className="verse-card-title"><h2>Мои карточки</h2><span>{available.length} осталось</span></div><div className="verse-card-list">{available.map(card => <button type="button" key={card.cardId} className={selected === card.cardId ? 'selected' : ''} onClick={() => setSelected(card.cardId)}><small>{card.direction === 'end' ? 'ОКОНЧАНИЕ' : 'НАЧАЛО'}</small>{card.fragment}</button>)}</div><button className="button verse-submit" disabled={busy || !selected || view.currentRound?.status !== 'open'} onClick={submit}>{busy ? 'Проверяем…' : 'Это мой стих'}</button>{error && <p className="connection-warning">{error}</p>}</section>{closed.length > 0 && <details className="verse-closed"><summary>Закрытые карточки ({closed.length})</summary>{closed.map(card => <article key={card.cardId} className={`status-${card.status}`}><b>{card.status === 'correct' ? 'Верно' : card.status === 'error' ? 'Ошибка' : 'Пропуск'}</b><p>{card.fullText}</p><small>{card.reference}</small></article>)}</details>}</>}
    {(view.phase === 'completed' || view.phase === 'closed') && <Surface className="verse-personal-result"><p className="eyebrow">{view.endedEarly ? 'ПРОМЕЖУТОЧНЫЙ ИТОГ' : 'МОЙ РЕЗУЛЬТАТ'}</p><h2>{view.result?.correct || 0} из {view.result?.total || view.stats.total}</h2><p>Ошибки: {view.result?.errors || 0} · пропуски: {view.result?.missed || 0}{view.result?.place ? ` · место: ${view.result.place}` : ''}</p></Surface>}
  </main>
}

export function VerseStagePage({ room = queryRoom() }: { room?: string }) {
  const [view, setView] = useState<VerseAudienceView | null>(null); const [error, setError] = useState('')
  useEffect(() => { void prepareVerseParticipantAuth().catch(reason => setError(errorText(reason))); return subscribeVerseAudience(room, setView, reason => setError(reason.message)) }, [room])
  if (!view) return <main className="verse-stage"><LoadingState eyebrow="СОБЕРИ СТИХ" title="Открываем экран…" description={error} /></main>
  return <main className="verse-stage"><header><p className="eyebrow">СОБЕРИ СТИХ · КОМНАТА {room}</p><h1>{view.title}</h1><span>{view.participantCount} участников</span></header>{view.phase === 'lobby' && <Surface><h2>Подключайтесь к игре</h2><p>После запуска здесь появится первый фрагмент.</p></Surface>}{view.phase === 'live' && <><div className="verse-stage-stats"><span>Раунд {view.roundNumber}</span><span>Осталось {view.remainingCards}</span></div><Surface className={`verse-prompt ${view.currentRound?.status === 'revealed' ? 'is-revealed' : ''}`}><p className="eyebrow">{view.currentRound?.status === 'revealed' ? 'ПОЛНЫЙ СТИХ' : view.currentRound?.promptDirection === 'start' ? 'НАЙДИТЕ НАЧАЛО' : 'НАЙДИТЕ ОКОНЧАНИЕ'}</p><blockquote>{view.currentRound?.status === 'revealed' ? view.currentRound.fullText : view.currentRound?.promptText}</blockquote>{view.currentRound?.status === 'revealed' && <><h2>{view.currentRound.reference}</h2><p>{view.currentRound.outcome === 'correct' ? `Нашёл: ${view.currentRound.answeredByName}` : 'Ответ показал ведущий'}</p></>}</Surface></>}{(view.phase === 'completed' || view.phase === 'closed') && <Surface><h2>{view.endedEarly ? 'Промежуточный итог' : 'Результаты'}</h2><ResultsTable rows={view.results || []} interim={view.endedEarly} /></Surface>}</main>
}

export function VerseParticipantPlaceholder(_props: ParticipantQuestionScreenProps) { return null }
